
*** Variables ***


#Scenario 1
${CHANNEL_NAME}   Jumpi071     #put channel name here


#Scenario 2
${video_1 & video_2 & video 3 ...}     sopa pá nois & Lady Gaga    #Place the video titles separated by '&'' here

#Scenario 3
${SEARCH_FIRST_ITEM}   hino do cruzeiro      #Place the text of the first item to be selected from the recommendation list here

#scenario 4
${NUMBER_OF_SHORTS}   2     #Place the number of shorts to be watched here